apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-api-server-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-api-server-cr
rules:
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-api-server-crb
subjects:
- namespace: busybox
  kind: ServiceAccount
  name: kube-api-server-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-api-server-cr
